version: '2'
services:
  sample-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/sample/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sample
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
